// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserStat.Models;

namespace UserStat.Migrations
{
    [DbContext(typeof(UserQueryContext))]
    [Migration("20220630104725_UpdateModels")]
    partial class UpdateModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UserStat.Models.QueriesBridge", b =>
                {
                    b.Property<long>("QueriesBridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("queryCreateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("query_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("user_id_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueriesBridgeId");

                    b.ToTable("QueriesBridges");
                });

            modelBuilder.Entity("UserStat.Models.Query", b =>
                {
                    b.Property<long>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("percent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("queryGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QueryId");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("UserStat.Models.QueryResult", b =>
                {
                    b.Property<long>("QueryResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("QueryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("count_sign_in")
                        .HasColumnType("INTEGER");

                    b.Property<string>("user_id")
                        .HasColumnType("TEXT");

                    b.HasKey("QueryResultId");

                    b.HasIndex("QueryId")
                        .IsUnique();

                    b.ToTable("QueryResult");
                });

            modelBuilder.Entity("UserStat.Models.UserQuery", b =>
                {
                    b.Property<long>("UserQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserQueryId");

                    b.ToTable("UserQueries");
                });

            modelBuilder.Entity("UserStat.Models.QueryResult", b =>
                {
                    b.HasOne("UserStat.Models.Query", "Query")
                        .WithOne("QueryResult")
                        .HasForeignKey("UserStat.Models.QueryResult", "QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("UserStat.Models.Query", b =>
                {
                    b.Navigation("QueryResult");
                });
#pragma warning restore 612, 618
        }
    }
}
