// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserStat.Models;

namespace UserStat.Migrations
{
    [DbContext(typeof(UserQueryContext))]
    [Migration("20220629110339_NewModelAttributes")]
    partial class NewModelAttributes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UserStat.Models.QueriesBridge", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("query_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("user_id_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("QueriesBridges");
                });

            modelBuilder.Entity("UserStat.Models.Query", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("percent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("queryGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("resultid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("resultid");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("UserStat.Models.QueryResult", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("count_sign_in")
                        .HasColumnType("INTEGER");

                    b.Property<string>("user_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("QueryResult");
                });

            modelBuilder.Entity("UserStat.Models.UserQuery", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("UserQueries");
                });

            modelBuilder.Entity("UserStat.Models.Query", b =>
                {
                    b.HasOne("UserStat.Models.QueryResult", "result")
                        .WithMany()
                        .HasForeignKey("resultid");

                    b.Navigation("result");
                });
#pragma warning restore 612, 618
        }
    }
}
